<a href="https://colab.research.google.com/github/PedroAlej0/ISIS1225-Laboratorio-3-prueba/blob/main/Tarea5/Punto_7_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [24]:
#proyeccion algebra lineal
def proyeccion_subespacion(v,u):
  a=np.zeros(np.shape(v))
  n=np.shape(u)[0]
  for i in range(n):
    z=(np.dot(u[i],v)*u[i])/(np.linalg.norm(u[i])**2)
    a+=z
    print(z)

  return a

In [25]:
v=np.array([-3, -3, 8, 9 ])
u=np.array([[3, 1, 0, 1],[1, 2, 1, 1],[-1, 0, 2, -1]])
proyeccion_subespacion(v,u)

[-0.81818182 -0.27272727  0.         -0.27272727]
[1.14285714 2.28571429 1.14285714 1.14285714]
[-1.66666667  0.          3.33333333 -1.66666667]


array([-1.34199134,  2.01298701,  4.47619048, -0.7965368 ])

In [4]:
Ut=u.T
Ut

array([[ 3,  1, -1],
       [ 1,  2,  0],
       [ 0,  1,  2],
       [ 1,  1, -1]])

In [16]:
def GaussJordan(A_, b_):

  A = A_.copy().astype(float)
  b = b_.copy().astype(float)
  n = A.shape[0]

  for i in range(n):
    for j in range(i+1,n):
      a = A[j,i]/A[i,i]
      A[j,:] -= a*A[i,:]
      b[j] -= a*b[i]


  x = np.zeros_like(b)

  for i in reversed(range(n)):

    x[i] = b[i]

    for j in range(i+1,n):

      x[i] -= A[i,j]*x[j]

    x[i] /= A[i,i]


  return x


In [20]:
ATA=np.dot(Ut.T,Ut)
b2=np.dot(Ut.T,v)

In [21]:
sol=GaussJordan(ATA,b2)
sol

array([-1.,  2.,  1.])

In [19]:
#proyeccion inimos cuadrados matriciales
np.dot(Ut,sol)

array([-2.00000000e+00,  3.00000000e+00,  4.00000000e+00,  1.08420217e-19],
      dtype=float128)

In [90]:
def gram_schmidt(vectors):
    num_vectors = vectors.shape[0]
    ortogonal = []
    for i in range(num_vectors):
        vec = vectors[i]
        for v in ortogonal:
            proj = np.dot(vec, v) / np.dot(v, v) * v
            vec = vec - proj
        ortogonal.append(vec)
    ortogonal = np.array(ortogonal)
    return ortogonal


Vectores ortogonales:
[[ 3.          1.          0.          1.        ]
 [-0.63636364  1.45454545  1.          0.45454545]
 [ 0.46341463 -0.48780488  1.41463415 -0.90243902]]


In [100]:
u = np.array([
    [3, 1, 0, 1],
    [1, 2, 1, 1],
    [-1, 0, 2, -1]])


ortogonal = gram_schmidt(u)
ortogonal

array([[ 3.        ,  1.        ,  0.        ,  1.        ],
       [-0.63636364,  1.45454545,  1.        ,  0.45454545],
       [ 0.46341463, -0.48780488,  1.41463415, -0.90243902]])

In [98]:
print(np.dot(ortogonal[0],ortogonal[1]))
print(np.dot(ortogonal[1],ortogonal[2]))
print(np.dot(ortogonal[0],ortogonal[2]))

#

4.440892098500626e-16
-1.1102230246251565e-16
-5.551115123125783e-16


In [102]:
for i in range(ortogonal.shape[0]):

    ortogonal[i]=ortogonal[i]/np.linalg.norm(ortogonal[i])

ortogonal


array([[ 0.90453403,  0.30151134,  0.        ,  0.30151134],
       [-0.32961713,  0.75341057,  0.51796977,  0.2354408 ],
       [ 0.25633581, -0.26982716,  0.78249877, -0.49918025]])

In [103]:
print(np.linalg.norm(ortogonal[0]))
print(np.linalg.norm(ortogonal[1]))
print(np.linalg.norm(ortogonal[2]))


1.0
1.0
1.0


In [106]:
c=np.zeros(np.shape(ortogonal)[0])
v=np.array([-3, -3, 8, 9 ])

In [108]:
for i in range(np.shape(ortogonal)[0]):
    c[i]=np.dot(ortogonal[i],v)
c

array([-0.90453403,  4.99134506,  1.807842  ])

In [114]:
#proyeccion base ortonormalizada,  Grand-Schmidt
pw=np.zeros(np.shape(v))
for i in range(np.shape(ortogonal)[0] ):
    pw+=c[i]*ortogonal[i]
pw


array([-2.00000000e+00,  3.00000000e+00,  4.00000000e+00, -1.11022302e-16])